// settings
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const TOGGLE_LOADING_SCREEN = 'TOGGLE_LOADING_SCREEN';
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const TOGGLE_GRID_LINES = 'TOGGLE_GRID_LINES';
export const TOGGLE_OSCILLATION = 'TOGGLE_OSCILLATION';
export const TOGGLE_PAUSE = 'TOGGLE_PAUSE';
export const SET_AMPLITUDE = 'SET_AMPLITUDE';
export const SET_NUMBER_OF_LINES = 'SET_NUMBER_OF_LINES';
export const SET_FREQUENCY = 'SET_FREQUENCY';
export const SET_STAGE_DIMENSIONS = 'SET_STAGE_DIMENSIONS';
export const SET_CHARGE_ORIGIN = 'SET_CHARGE_ORIGIN';
export const SET_CHARGE_OSCILLATION = 'SET_CHARGE_OSCILLATION';
export const SET_TIMER_COUNT = 'SET_TIMER_COUNT';
export const SET_ELAPSED_TIME = 'SET_ELAPSED_TIME';
