// settings
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const TOGGLE_LOADING_SCREEN = 'TOGGLE_LOADING_SCREEN';
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const TOGGLE_OSCILLATION = 'TOGGLE_OSCILLATION';
export const SET_AMPLITUDE = 'SET_AMPLITUDE';
