// settings
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const TOGGLE_LOADING_SCREEN = 'TOGGLE_LOADING_SCREEN';
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const TOGGLE_GRID_LINES = 'TOGGLE_GRID_LINES';
export const TOGGLE_OSCILLATION = 'TOGGLE_OSCILLATION';
export const TOGGLE_PAUSE = 'TOGGLE_PAUSE';
export const SET_AMPLITUDE = 'SET_AMPLITUDE';
export const SET_NUMBER_OF_LINES = 'SET_NUMBER_OF_LINES';
export const ADJUST_FREQUENCY = 'ADJUST_FREQUENCY';
